INSERT INTO tb_genre (name)  VALUES ('Ação');
INSERT INTO tb_genre (name)  VALUES ('Aventura');
INSERT INTO tb_genre (name)  VALUES ('Mistério'); 
INSERT INTO tb_genre (name)  VALUES ('Romance');
INSERT INTO tb_genre (name)  VALUES ('Suspense');
INSERT INTO tb_genre (name)  VALUES ('Comédia'); 
INSERT INTO tb_genre (name)  VALUES ('Crime');
INSERT INTO tb_genre (name)  VALUES ('Animação');
INSERT INTO tb_genre (name)  VALUES ('Fantasia'); 
INSERT INTO tb_genre (name)  VALUES ('Terror'); 


INSERT INTO tb_role (authority)  VALUES ('VISITOR');
INSERT INTO tb_role (authority)  VALUES ('MEMBER');
 
INSERT INTO tb_user (name, email, password) VALUES ('Alex Brown', 'alex@gmail.com', '$2a$10$HSfDbwxcMCQs3xVVSDWYwu32/uZ4jgTWVz.hU3W8APxb9Z4FYf0O6');
INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$SqhHVe6KmO/qCm/irKBmoeDz36xydIFjqft3gkP5z1Lj49zECiIQq');
INSERT INTO tb_user (name, email, password) VALUES ('Maria', 'maria@gmail.com', '$2a$10$2ppHgi1XTTjYSgbQri.SBeV77t2eWdUaqPrrB7hELKfU8381PXzv2');
INSERT INTO tb_user (name, email, password) VALUES ('João Otávio', 'joao@gmail.com', '$2a$10$a0xXM7es.VsZjCGFUz9DOOYlpNYcBwE/nX/Ew8fLXEeWT6pnyqqvm');
INSERT INTO tb_user (name, email, password) VALUES ('Ana Carla', 'ana@gmail.com', '$2a$10$eBQbNsFz7trzcw1xDuF0zOudQUMNih4Q4YQmry346bORYz2KeWFny');

INSERT INTO tb_user_role (user_id, role_id)  VALUES (1, 2);
INSERT INTO tb_user_role (user_id, role_id)  VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id)  VALUES (3, 1);
INSERT INTO tb_user_role (user_id, role_id)  VALUES (4, 2);
INSERT INTO tb_user_role (user_id, role_id)  VALUES (5, 2);



INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BNTkwOTE1ZDYtODQ3Yy00YTYwLTg0YWQtYmVkNmFjNGZlYmRiXkEyXkFqcGdeQXVyNTc4MjczMTM@._V1_FMjpg_UX864_.jpg','O vilão Loki reempreende seu papel como o Deus do Mal....', 'O vilão Loki reempreende seu papel como o Deus do Mal em uma nova série que ocorre após os eventos de "Vingadores: Ultimato".', 'Loki', 2021,9);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMTE2ODU4NDEtNmRjNS00OTk1LTg4NmMtNTAzYzVlNzJmYjgzXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_QL75_UX380_CR0,0,380,562_.jpg','Um filme de terror','Após os eventos em casa, a família Abbott agora enfrenta os terrores do mundo exterior. Forçados a se aventurar no desconhecido, eles percebem que as criaturas que caçam não são as únicas ameaças ocultas pelo caminho.','Um Lugar Silencioso: Parte II',2020,10);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BZTQyNTU0MDktYTFkYi00ZjNhLWE2ODctMzBkM2U1ZTk3YTMzXkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_QL75_UX380_CR0,0,380,562_.jpg','É assim que uma nova amizade começa','Na Riviera italiana, uma amizade tão forte quanto inesperada surge entre um ser humano e um monstro marinho camuflado.','Luca',2021,8);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BOWI5YTUxOWEtZmRiZS00ZmQxLWE2NzctYTRiODA2NzE1ZjczXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_QL75_UX380_CR0,0,380,562_.jpg','Conheça as origens de Cruella','Uma prequela sobre a vida da jovem Cruella de Vil.','Cruella',2021,6);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BZGEwYmMwZmMtMTQ3MS00YWNhLWEwMmQtZTU5YTIwZmJjZGQ0XkEyXkFqcGdeQXVyMTI5MzA5MjA1._V1_QL75_UX380_CR0,4,380,562_.jpg','Uma comédia intrigante','Ao viverem sua vida suburbana ideal, Wanda Maximoff e Vision começam a suspeitar que as coisas não são o que parecem.','WandaVision',2021,6);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BODNiODVmYjItM2MyMC00ZWQyLTgyMGYtNzJjMmVmZTY2OTJjXkEyXkFqcGdeQXVyNzk3NDUzNTc@._V1_QL75_UX380_CR0,0,380,562_.jpg','Uma produção conjunta da Disney e Marvel','Uma produção da Disney e da Marvel Studios, estrelando os personagens carismáticos Falcão e Soldado Invernal.','Falcão e o Soldado Invernal',2021,2);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMjM5YTRlZmUtZGVmYi00ZjE2LWIyNzAtOWVhMDk1MDdkYzhjXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_QL75_UX380_CR0,20,380,562_.jpg','O protagonista está sob a mira de um traficante perigoso','Um garoto intervém para ajudar uma mulher sendo assediada por um grupo de homens, ele se torna o alvo de um traficante vingativo.','Anônimo',2021,1);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_QL75_UX380_CR0,0,380,562_.jpg','Muito horror com monstros com audição sensível','Em um mundo pós-apocalíptico, uma família é forçada a viver em silêncio enquanto se esconde de monstros com audição ultra-sensível.','Um Lugar Silencioso', 2018, 10);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BNGVkOTlhOTktNjZiNS00NDg3LWIxMDAtZTY5Y2E0YjllN2IxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_QL75_UX380_CR0,0,380,562_.jpg','O enredo envolve uma personagem fria e misteriosa','O enredo segue-se a H, uma personagem fria e misteriosa que trabalha numa empresa de camiões de dinheiro responsável pela movimentação de centenas de milhões de dólares em Los Angeles todas as semanas.','Infiltrado',2021,1);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'Sequência de vingadores guerra infinita','Após os eventos devastadores de Vingadores: Guerra Infinita , o universo está em ruínas, e com a ajuda de aliados os Vingadores se reúnem para desfazer as ações de Thanos e restaurar a ordem.', 'Vingadores: Ultimato', 2019, 2);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMTM1MTk2ODQxNV5BMl5BanBnXkFtZTcwOTY5MDg0NA@@._V1_QL75_UX380_CR0,4,380,562_.jpg', 'Uma nova aventura de James Bond', 'Agent James Bond 007 (Pierce Brosnan) is on a mission which includes a media tycoon,... Chinese waters. Bond gains the help of Wai Lin (Michelle Yeoh) on his quest to stop him, but how will Bond feel when he meets up with his former lover, Paris (Teri Hatcher), who is now Carvers wife.', '007 - O Amanhã Nunca Morre', 1997, 1);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMjA0MzUyNjg0MV5BMl5BanBnXkFtZTcwNDY5MDg0NA@@._V1_QL75_UX380_CR0,4,380,562_.jpg', 'Quando a nova missão do agente 007', 'Quando a nova missão do agente 007 é proteger uma herdeira do petróleo, ele é catapultado para uma aventura que o coloca contra um mortífero adversário: Renard, um anarquista cuja total insensibilidade à dor o torna imparável.', '007 - O Mundo Não é o Bastante', 1999, 1); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMjZiYTUzMzktZWI5Yy00Mzk4LWFlMDgtYjRmNWU0Mzc0MzNiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_QL75_UX380_CR0,1,380,562_.jpg', 'James Bond mergulha em', 'James Bond mergulha em mistério ao tentar impedir que uma organização misteriosa elimine o recurso mais valioso de um país.', '007 - Quantum of Solace', 2008, 1); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BNjY2Mzc0MDA4NV5BMl5BanBnXkFtZTcwOTg5OTcxNw@@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'Abraham Lincoln, décimo sexto presidente', 'Abraham Lincoln, décimo sexto presidente dos Estados Unidos, descobre que os vampiros planejam dominar os Estados Unidos, mas ele tem a missão de eliminá-los.', 'Abraham Lincoln: Caçador de Vampiros', 2012, 9); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMzc2NDMzNDY4Ml5BMl5BanBnXkFtZTYwNzM2Njk3._V1_QL75_UX380_CR0,0,380,562_.jpg', 'No passado pré-histórico, DLeh é um caçador', 'No passado pré-histórico, DLeh é um caçador gigantesco que se une ao belo Evolet. Quando os guerreiros a cavalo capturam Evolet e os homens tribais, DLeh deve embarcar em uma odisséia para salvar seu verdadeiro amor.', '10.000 A.C.', 2008, 2); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMTY3MTY3MzkzNl5BMl5BanBnXkFtZTYwNTAwNDk2._V1_QL75_UY562_CR11,0,380,562_.jpg', 'O Dr. Josh Keyes fez uma terrível ', 'O Dr. Josh Keyes fez uma terrível descoberta: o núcleo do planeta parou de girar e o campo electromagnético está a degradar-se. Mas existe uma esperança: enviar Keyes e um grupo de cientistas ao núcleo da Terra para reactivar a rotação.', 'O Núcleo: Missão ao Centro da Terra', 2003, 2); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BODg1YWNjNjctOGJiYi00YzRjLWI2ZWYtMTAxZGM5ODY1Yzc4XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'Uma mulher dentro de uma história', 'Uma mulher dentro de uma história de quadrinhos procura seduzir seu criador para passar ao mundo real.', 'Mundo Proibido', 1992, 9); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMTM0MTg3OTU5N15BMl5BanBnXkFtZTYwMDc4MzU3._V1_QL75_UX380_CR0,1,380,562_.jpg', 'Os Angeles investigam', 'Os Angeles investigam uma série de assassinatos que ocorreram após o roubo de um banco de dados de proteção a testemunhas.', 'As Panteras: Detonando', 2003, 6); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMGI1NTM5MTItNDcxMS00YTIwLTg1NjUtNzE5ZGE5NDkxMmU4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL75_UX380_CR0,6,380,562_.jpg', 'Três detetives com', 'Três detetives com um chefe misterioso recuperam um software de identificação de voz roubado, usando artes marciais, suas habilidades e seu sex appeal.', 'As Panteras', 2000, 6); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMmRmODc1OGEtYzhjOC00Y2FiLWFhNWUtYTJiYjlhMGU0Njk4XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'Um jovem recebe', 'Um jovem recebe uma chamada de emergência em seu celular de uma mulher mais velha. A pegada? A mulher afirma ter sido sequestrada; e os sequestradores têm como alvo seu marido e filho em seguida.', 'Celular: Um Grito de Socorro', 2004, 7); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMTEwODkxNzE4NzVeQTJeQWpwZ15BbWU3MDY5NDYwMzQ@._V1_QL75_UX380_CR0,4,380,562_.jpg', 'Um monge tibetano', 'Um monge tibetano se torna o mentor de um garoto da rua que ele pode ensinar a proteger um pergaminho.', 'O Monge à Prova de Balas', 2003, 9); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMTA4OTA4Njk4MDdeQTJeQWpwZ15BbWU3MDc0NDY1MzM@._V1_QL75_UY562_CR1,0,380,562_.jpg', 'Lutando para se recuperar', 'Lutando para se recuperar emocionalmente de uma agressão brutal que matou seu noivo e a deixou em coma, uma personalidade de rádio começa uma vingança contra os perpetradores, o que deixa um rastro sangrento em Nova York.', 'Valente', 2007, 7); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMWM5N2M1NmEtMmNkNC00MTg1LThlOGItZWMxMDlkNTY5ZTk2XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_QL75_UY562_CR21,0,380,562_.jpg', 'Uma comédia de ação', 'Uma comédia de ação centrada em uma mulher obesa cujos passos causam explosões e suas espadas duplas são usadas contra qualquer um que zombe dela.', 'Blubberella', 2011, 6); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMTUzMjM0MTc3MF5BMl5BanBnXkFtZTcwNzU0ODMyMw@@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'O guerreiro Beowulf', 'O guerreiro Beowulf deve lutar e derrotar o monstro Grendel, que está aterrorizando a Dinamarca.', 'A Lenda de Beowulf', 2007, 8); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMGE1ZTQ0ZTEtZTEwZS00NWE0LTlmMDUtMTE1ZWJiZTYzZTQ2XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'Dois detetives protegem', 'Dois detetives protegem a testemunha de um assassinato enquanto investigam um caso de heroína, que foi roubado do depósito de evidências da polícia.', 'Os Bad Boys', 1995, 7); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BZmU4NzVkZjEtZmQxMi00ZDY5LWI3ZDYtMWRmZjE5YmYwZjQzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL75_UX380_CR0,1,380,562_.jpg', 'Os detetives da Narcóticos', 'Os detetives da Narcóticos Marcus Burnett e Mike Lowrey são designados para investigar a proliferação do ecstasy na cidade de Miami.', 'Os Bad Boys II', 2003, 7); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMTI4NTgyOTIxN15BMl5BanBnXkFtZTYwMTUwODY3._V1_QL75_UX380_CR0,0,380,562_.jpg', 'Através de um misterioso portal', 'Através de um misterioso portal temporal, um filho comunica com o seu pai, falecido precocemente há trinta anos, através de um velho rádio amador. Os dois vão tentar manipular o passado de modo a evitar a morte e alterar o futuro.', 'Alta Frequência', 2000, 3); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BY2ZlMTM2ZGEtNTFkYy00NTMzLTgwZmUtNGVhOTY1ZmQ5NmZlXkEyXkFqcGdeQXVyMjY2NzIyNjI@._V1_QL75_UX380_CR0,7,380,562_.jpg', 'When a young womans boyfriend dies', 'When a young womans boyfriend dies, she slips into grief and begins to believe that his spirit has returned in the form of a menacing skeleton doll.', 'After the Flesh', 2019, 4); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BZTViYzM3MWYtM2IzMC00NjMwLWE2ZDQtMTQ1YmE5NGE0MTU5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL75_UX380_CR0,1,380,562_.jpg', 'Depois que a sua fuga falha', 'Depois que a sua fuga falha, uma mulher apavorada se fortalece para lutar contra seu marido abusivo.', 'Nunca Mais', 2002, 5); 
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id)  VALUES ('https://m.media-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'Um militar paraplégico', 'Um militar paraplégico despachado para a lua Pandora em uma missão única fica dividido entre seguir suas ordens e proteger o mundo que ele sente ser sua casa.', 'Avatar', 2009, 9); 

INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Achei o filme ótimo, meus parabéns para o diretor!!!', 1, 2);
